name: Update Chrome Extension Version

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Update Chrome Extension Version
        run: |
          # Read the current version from update-manifest.json
          current_version=$(jq -r '.version' update-manifest.json)
          
          # Increment the version (e.g., 1.0.0 -> 1.0.1)
          new_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          
          # Update the version in update-manifest.json
          jq --arg new_version "$new_version" '.version = $new_version' update-manifest.json > manifest.tmp && mv manifest.tmp update-manifest.json
          
          # Commit the changes
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add update-manifest.json
          git commit -m "Auto-update extension version to $new_version"
          git push
